### ISSUE TITLE
syntax highlight for v-model, custom directives

### ISSUE THREAD

**Issue by troglotit** [AdamNiederer/vue-html-mode#4]
Hey! I've been using vue-mode for quite some time and it works great! But yeah, not a lot of frontend developers use emacs so stuff is not working from time to time 😅.

Here's the image of broken syntax highlight:
![image](https://user-images.githubusercontent.com/10955264/30027106-2a59379c-9188-11e7-8977-b345be9fb637.png)

**Comment by AdamNiederer** [comment]
Hi there,

Thanks for your report. I've pushed a [series](https://github.com/AdamNiederer/vue-html-mode/commit/02fc90dc8ea87261ea4768993ff762e5b719cb33) [of](https://github.com/AdamNiederer/vue-html-mode/commit/e5815314abd2440cca88736f6cef096a4b6a6d16) [commits](https://github.com/AdamNiederer/vue-html-mode/commit/7358de66280435531dda4dd29dfbcef397edb628) which should alleviate your second problem.

I'm having issues reproducing the busted v-model highlihting, however. It looks like it's of a different face than the equals sign in your screenshot. Could you put your cursor over v-model, type `M-x describe-face RET RET`, and give me the face which is described? It should be `font-lock-builtin-face`.

**Comment by troglotit** [comment]
```
Face: mmm-default-submode-face (sample) (customize this face)

Documentation:
Face used for all submodes at decoration level 1.
Also used at decoration level 2 for submodes not specifying a type.

Defined in ‘mmm-vars.el’.

           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: gray20
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
          Inherit: unspecified
```
And I'll try to update after new MELPA builds

**Comment by AdamNiederer** [comment]
Hm, I think mmm-mode is overriding the description of face set by vue-html-mode. Could you paste the troublesome template into a buffer, activate vue-html-mode (`M-x vue-html-mode`), and try that again?

**Comment by troglotit** [comment]
After update, it still renders just like
![image](https://user-images.githubusercontent.com/10955264/30050721-21361432-9228-11e7-9364-e204bd95bbce.png)
And second case in first screenshot is like this
![image](https://user-images.githubusercontent.com/10955264/30050766-46c03606-9228-11e7-91f5-8abc80a39a87.png)

```
Face: font-lock-builtin-face (sample) (customize this face)

Documentation:
Font Lock mode face used to highlight builtins.

Defined in ‘font-lock.el’.

           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: bold
            Slant: unspecified
       Foreground: #DCDCCC
DistantForeground: unspecified
       Background: unspecified
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
          Inherit: unspecified

[back]
```
